import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/header";
import Background from "./_components/background/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Classifruit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background>
          <Header />
          {children}
        </Background>
      </body>
    </html>
  );
}
